import myLabel from '../../components/label/Label.vue'

export default {
  name: 'Article',
  props: {
    is_review: {
      type: Boolean,
      default: false
    },
    is_autogenerated: {
      type: Boolean,
      default: false
    },
    labelText: {
      type: String,
      // required: true
    },
    labelType: {
      type: String,
      // required: true
    },
    articleTitle: {
      type: String,
      // required: true
    }
  },
  components: {
    myLabel
  },
  data: function() {
    return {
    }
  },
  methods: {
  }
}